### ISSUE TITLE
Serving Docker-NagiosXi over SSL secured Nginx reverse proxy causes errors

### ISSUE THREAD

**Issue by PSPanesar** [tgoetheyn/Docker-NagiosXI#2]
Hi,

I'm serving the docker-nagiosXi on my server using nginx as a reverse proxy and the domain is secured using SSL in nginx. I've had lots of problems with errors when using the container in reverse proxy with unsecured scripts. Is there a way to set use of SSL for the container?

Bw
P

**Comment by tgoetheyn** [comment]
Hi,

I build the Nagios XI container a long time ago.
because I now have a full QA setup I don't put any work in it anymore.

for SSL implementation I presume you'll have to rebuild the docker image and expose port 443 for SSL.
because the dockerfile is based on an old install script, it probably wil need some adjustments.

feel free to fork the project and make a pull request with the adjustments.

**Comment by PSPanesar** [comment]
Hi. Thanks for your reply. I’ll fork the project and try and implement changes to allow it to work behind a nginx ssl secured server. The setup has nginx forward traffic to the Docker nagios server port by reverse proxy the ssl secured traffic. I’m fairly new to Docker so not sure I can solve this one :). Bw

**Comment by tgoetheyn** [comment]
This was also my first docker image, so it isn't that complicated ;-)
Succes!
